# idp.ini

#
# KeyStore Management.
# In the following
#     "idp.backchannel.*" refers to the TLS connection on the SOAP port (8443)
#     "jetty.sslContext.*" refers to the TLS connection on 443

jetty.sslContext.keyStorePath=/etc/letsencrypt/live/fedmanagertest.learn.ac.lk/keystore.p12
jetty.sslContext.trustStorePath=/etc/letsencrypt/live/fedmanagertest.learn.ac.lk/truststore.p12
jetty.sslContext.trustStorePassword=learn123

# Keystore types
jetty.sslContext.keyStoreType=PKCS12

# Keystore passwords
jetty.sslContext.keyStorePassword=learn123
